### ISSUE TITLE
JWS zips in playbook directory

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws#127]
##### SUMMARY
In chapter Using JWS local zipfiles, it's mentioned that zipfiles need to be in playbook directory. That statement is incorrect as the zipfiles have to be in $PWD, not where the playbook resides.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.9.27
```

##### COLLECTION VERSION

```
1.1.1
```

##### STEPS TO REPRODUCE

Create host file with managed nodes, create playbook and run it.
```
ansible-playbook -i hosts playbooks/jws.yml
```

```yaml
---

- name: "Install JWS with natives from controller zip files"
  hosts: managed-nodes
  vars:
    tomcat_install_method: rhn_zipfiles
    jws_version: 5.6.0
    tomcat_setup: true
  roles:
    - jws
```

##### EXPECTED RESULTS

Playbook passes.

##### ACTUAL RESULTS

```
TASK [github.jws.jws : Check downloaded archive /home/akrajcik/workspaces/ansible/github/jws/jws-5.6.0-application-server.zip] ************************************************************************************************************
ok: [managed-node-one -> localhost]

TASK [github.jws.jws : Install JWS with zipfile from RHN: https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=103663] **************************************************************************************
fatal: [managed-node-one -> localhost]: FAILED! => {"changed": false, "msg": "An error occurred retrieving content"}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************
managed-node-one           : ok=30   changed=1    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0
```
