### ISSUE TITLE
Preinstalled Java

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws#206]
##### SUMMARY

If I have preinstalled Java, it isn't picked up.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.12.2
```

##### COLLECTION VERSION

```
1.2.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Install JWS with ZIPs
  hosts: instance
  vars:
    jws_version: "{{ ews_version }}"
    jws_systemd_enabled: True
  tasks:
    - name: Import JWS role
      import_role:
        name: "{{ test_collection if test_collection is defined else 'redhat.jws'}}.jws"
```

##### EXPECTED RESULTS

Service has started. Tomcat is running.

##### ACTUAL RESULTS

```
/opt/jws-5.6/tomcat/bin/catalina.sh: line 504: /usr/lib/jvm/java/bin/java: No such file or directory\n/opt/jws-5.6/tomcat/bin/catalina.sh: line 504: /usr/lib/jvm/java/bin/java: No such file or directory
```
