### ISSUE TITLE
Natives patch not applied.

### ISSUE THREAD

**Issue by AdamKrajcik** [ansible-middleware/jws#207]
##### SUMMARY

When applying patches, native zip is not applied.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.12.2]
```

##### COLLECTION VERSION

```
1.2.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Install JWS with ZIPs
  hosts: instance
  vars:
    jws_version: "5.6.0"
    jws_native: True
    jws_apply_patches: True
  tasks:
    - name: Import JWS role
      import_role:
        name: "redhat.jws.jws"
```

##### ACTUAL RESULTS

```
TASK [redhat.jws.jws : Update /opt/jws-5.6/tomcat with downloaded Cumulative Patch /opt/jws-5.6.2-application-server.zip.] ***
changed: [instance]

TASK [redhat.jws.jws : Set checksum file] **************************************
changed: [instance]

TASK [redhat.jws.jws : Set target architecture for native patch.] **************
skipping: [instance]

TASK [redhat.jws.jws : Download native patch from RHN (if credentials provided).] ***
skipping: [instance]

TASK [redhat.jws.jws : Ensure /opt/jws-5.6/tomcat/ directories have appropriate privileges] ***
ok: [instance] => (item=conf)
ok: [instance] => (item=temp)
ok: [instance] => (item=logs)
ok: [instance] => (item=webapps)
ok: [instance] => (item=bin)


```
