### ISSUE TITLE
Selinux is not working.

### ISSUE THREAD

**Issue by AdamKrajcik** [ansible-middleware/jws#209]
##### SUMMARY

During variable transformation, values for expected filenames have changed and it's causing the tasks to be skipped even though jws_selinux_enabled is set to True.

##### ISSUE TYPE
 - Bug Report

##### COLLECTION VERSION

```
1.2.1
```

##### STEPS TO REPRODUCE

```yaml
---

- name: Install JWS with ZIPs
  hosts: managed-nodes
  vars:
    jws_version: "5.6.0"
    jws_natice: True
    jws_selinux_enabled: True
  tasks:
    - name: Import JWS role
      import_role:
        name: "redhat.jws.jws"
```

##### ACTUAL RESULTS

```
TASK [redhat.jws.jws : Install selinux-policy-devel] **************************************************************************************************************************************************************************************
skipping: [managed-node-two]

TASK [redhat.jws.jws : Check if archive contains a selinux policy] ************************************************************************************************************************************************************************
skipping: [managed-node-two]

TASK [redhat.jws.jws : Create selinux policy] *********************************************************************************************************************************************************************************************
skipping: [managed-node-two]

```
