### ISSUE TITLE
Collection doesn't recognize native resources zip with new JWS version

### ISSUE THREAD

**Issue by AdamKrajcik** [ansible-middleware/jws#243]
##### SUMMARY
With JWS 6 release, the zip for platform specific resources has changed its name. Instead of `application-server`,
the zip has `optional-native-components` in its name.  This new naming is only for JWS 6. The naming for the old versions stays the same.

##### ISSUE TYPE
 - Bug Report

##### COLLECTION VERSION

```
1.2.4
```

##### STEPS TO REPRODUCE

```yaml
- name: Install JWS with ZIPs
  hosts: instance
  vars:
    jws_version: "6.0.0.EA"
    jws_java_version: 11
    jws_native: True
    jws_systemd_enabled: True
    jws_listen_https_enabled: True
  tasks:
    - name: Import JWS role
      import_role:
        name: "redhat.jws.jws"
```

##### ACTUAL RESULTS

```
TASK [redhat.jws.jws : Install Jboss Web Server and required binaries from local zipfiles (install method: zipfiles)] ***
failed: [instance] (item={'src': 'jws-6.0.0.EA-application-server-RHEL8-x86_64.zip', 'creates': '/opt/jws-6.0/tomcat/lib/libtcnative-1.so'}) => {"ansible_loop_var": "item", "changed": false, "item": {"creates": "/opt/jws-6.0/tomcat/lib/libtcnative-1.so", "src": "jws-6.0.0.EA-application-server-RHEL8-x86_64.zip"}, "msg": "Source '/opt/jws-6.0.0.EA-application-server-RHEL8-x86_64.zip' does not exist"}
```
